### ISSUE TITLE
Error in api/webhook/.assistantRequest.ts

### ISSUE THREAD

**Issue by leeparnell** [VapiAI/server-side-example-serverless-vercel#2]
Whenever I try to follow the tutorial to get the server up I get the following error. 

```
Error: api/webhook/.assistantRequest.ts(60,27): error TS2322: Type '{ name: string; model: { provider: string; model: string; temperature: number; messages: { role: string; content: string; }[]; functions: { name: string; description: string; parameters: { type: string; properties: { ...; }; required: string[]; }; }[]; }; voice: { ...; }; firstMessage: string; }' is not assignable to type 'Assistant'.
  The types of 'model.messages' are incompatible between these types.
    Type '{ role: string; content: string; }[]' is not assignable to type 'ChatCompletionMessageParam[]'.
      Type '{ role: string; content: string; }' is not assignable to type 'ChatCompletionMessageParam'.
        Property 'name' is missing in type '{ role: string; content: string; }' but required in type 'ChatCompletionFunctionMessageParam'.
```

This error shows up in editor, VSCode, or whenever I ignore the error and attempt `pnpm deploy:prod`. 
The error seems to be in the defined types found in `server-side-example-serverless-vercel/types/vapi.types.ts`  and used in `server-side-example-serverless-vercel/api/webhook/.assistantRequest.ts` 

Is there anything I'm missing her to resolve this issue?

**Comment by nikhilro** [comment]
I think something must be out of date. Try `as any`. https://api.vapi.ai/api is always the ground truth on current schema

**Comment by leeparnell** [comment]
Thanks for the response @nikhilro . It's good to know where the ground truth api is. But it doesn't help the current problem which is is the example code won't deploy/run. So at this point I'm not even using the actual api.

**Comment by nikhilro** [comment]
cc @kaustubhkagrawal

**Comment by kaustubhkagrawal** [comment]
@leeparnell Pushed the changes. The typescript wasn't able to resolve types for messages of the plain javascript defined in `api/webhook/.assistantRequest.ts` file.
